language: android
sudo: false
android:
  components:
    - android-9
jdk:
  - oraclejdk8
  - oraclejdk7
install: gradle assemble
script: gradle check
after_success:
  gradle jacocoRootReport coveralls
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
